apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer  # Use LoadBalancer or NodePort depending on your setup
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 5000  # Port on which the container is listening
